-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 25, 2024 at 12:11 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `consoleverse_website`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `prod_id` int(11) NOT NULL,
  `brand` varchar(30) NOT NULL,
  `model` varchar(30) NOT NULL,
  `descrip` varchar(300) NOT NULL,
  `short_desc` varchar(100) NOT NULL,
  `cpu` varchar(50) NOT NULL,
  `gpu` varchar(50) NOT NULL,
  `memory` varchar(50) NOT NULL,
  `storage` varchar(60) NOT NULL,
  `price` decimal(9,2) NOT NULL,
  `img` varchar(100) NOT NULL,
  `rating` int(11) NOT NULL,
  `stock` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`prod_id`, `brand`, `model`, `descrip`, `short_desc`, `cpu`, `gpu`, `memory`, `storage`, `price`, `img`, `rating`, `stock`) VALUES
(1, 'PlayStation', '5 Refined', 'The PS5 Refined sets the standard for next-generation gaming, boasting lightning-fast load times, stunning 4K visuals, and immersive 3D audio. Its innovative DualSense controller brings games to life ', '1TB SSD, Ray-Tracing, 4K 120FPS', 'Custom AMD Zen 2', 'AMD RDNA 2', '16GB GDDR6', '1TB SSD', 479.00, 'Images/PS5Refined.jpg', 5, 8),
(2, 'PlayStation', '5 Digital Refined', 'Experience the future of gaming with the PS5 Refined Digital. Enjoy the same powerful performance and breath-taking graphics as the PS5 Refined, but in a sleek, all-digital package.', '1TB SSD, Ray-Tracing, 4K 120FPS, Disc-less', 'Custom AMD Zen 2', 'AMD RDNA 2', '16GB GDDR6', '1TB SSD', 379.00, 'Images/PS5DigitalRefined.jpg', 5, 4),
(3, 'PlayStation', '5', 'The PS5 delivers cutting-edge gaming technology with its lightning-fast SSD, ray tracing capabilities, and high frame rates. Its innovative DualSense controller offers immersive feedback.', '825GB SSD, Ray-Tracing, 4K 120FPS', 'Custom AMD Zen 2', 'AMD RDNA 2', '16GB GDDR6', '825GB SSD', 449.00, 'Images/PS5.jpg', 5, 7),
(4, 'PlayStation', '5 Digital', 'Dive into a digital world of gaming with the PS5 Digital Edition. With no disc drive, this console offers faster load times, smoother gameplay, and access to a vast library of digital titles.', '825GB SSD, Ray-Tracing, 4K 120FPS, Disc-less', 'Custom AMD Zen 2', 'AMD RDNA 2', '16GB GDDR6', '825GB SSD', 359.00, 'Images/PS5Digital.jpg', 5, 6),
(5, 'PlayStation', '4 Pro', 'The PS4 Pro enhances your gaming experience with 4K resolution, HDR technology, and smoother frame rates. Immerse yourself in breath-taking worlds with enhanced graphics and performance.', '1TB HDD, 4K, HDR', ' AMD Jaguar', 'AMD Radeon', '8GB GDDR5', '1TB HDD', 329.00, 'Images/PS4Pro.jpg', 4, 8),
(6, 'PlayStation', '4 Pro', 'The PS4 Pro enhances your gaming experience with 4K resolution, HDR technology, and smoother frame rates. Immerse yourself in breath-taking worlds with enhanced graphics and performance.', '2TB HDD, 4K, HDR', 'AMD Jaguar', 'AMD Radeon', '8GB GDDR5', '2TB HDD', 399.00, 'Images/PS4Pro.jpg', 4, 2),
(7, 'PlayStation', '4 Slim', 'The PS4 Slim combines sleek design with powerful performance, offering vibrant HDR gaming and streaming capabilities. Its compact size makes it perfect for any living space.', '500GB HDD, HDR, Power-Efficient', 'AMD Jaguar', 'AMD Radeon', '8GB GDDR5', '500GB HDD', 249.00, 'Images/PS4Slim.jpg', 4, 4),
(8, 'PlayStation', '4 Slim', 'The PS4 Slim combines sleek design with powerful performance, offering vibrant HDR gaming and streaming capabilities. Its compact size makes it perfect for any living space.', '1TB HDD, HDR, Power-Efficient', 'AMD Jaguar', 'AMD Radeon', '8GB GDDR5', '1TB HDD', 299.00, 'Images/PS4Slim.jpg', 4, 5),
(9, 'PlayStation', '4', 'The PS4 offers incredible gaming power and entertainment features, including Blu-ray playback and access to streaming services. Dive into a vast library of games and experience immersive gameplay.', '500GB HDD, Blue-Ray Player', 'AMD Jaguar', 'AMD Radeon', '8GB GDDR5', '500GB HDD', 229.00, 'Images/PS4.jpg', 4, 6),
(10, 'PlayStation', '4', 'The PS4 offers incredible gaming power and entertainment features, including Blu-ray playback and access to streaming services. Dive into a vast library of games and experience immersive gameplay.', '1TB HDD, Blue-Ray Player', 'AMD Jaguar', 'AMD Radeon', '8GB GDDR5', '500GB HDD', 279.00, 'Images/PS4.jpg', 4, 3),
(11, 'PlayStation', '', 'The original PlayStation, also known as PS1, revolutionized the gaming industry with its 3D graphics and extensive game library.', 'Classic PS1 Console, CD-ROM, Memory Cards', 'MIPS R3000A', '2D Graphics Engine', '2MB RAM', 'CD-ROM Drive', 55.00, 'Images/PS1.jpg', 4, 9),
(12, 'PlayStation', 'One', 'The original PSOne, a refined version of the PS1 which grew the gaming industry with its 3D graphics and extensive game library.', 'Classic PSOne Console, CD-ROM, Memory Cards', 'MIPS R3000A', '2D Graphics Engine', '2MB RAM', 'CD-ROM Drive', 47.00, 'Images/PSOne.jpg', 3, 3),
(13, 'PlayStation', '2', 'The PS2 is one of the best-selling consoles of all time, offering a vast library of games and multimedia features. Its backward compatibility with PS1 games makes it a must-have for gaming enthusiasts.', 'PS1 Game Compatible, HDD Expandable', '128-bit Emotion Engine CPU', '', '32MB RAM', 'DVD-ROM Drive', 64.00, 'Images/PS2.jpg', 4, 11),
(14, 'PlayStation', '2 Slim', 'The PS2 Slim retains all the features of the original PS2 but in a more compact and lightweight form factor. It\'s perfect for gamers who want to save space without sacrificing performance.', 'PS1 Game Compatible, Slimer PS2', '128-bit Emotion Engine CPU', '', '32MB RAM', 'DVD-ROM Drive', 69.00, 'Images/PS2Slim.jpg', 4, 8),
(15, 'PlayStation', '3', 'The PS3 offers an extensive library of games and PS2, PS1 capabilities. While it\'s an older model, it provides solid performance and entertainment value.', 'PS2, PS1 Game Compatible, 160GB HDD', 'Cell Broadband Engine CPU', 'NVIDIA RSX GPU', '256MB RAM', '160GB HDD', 120.00, 'Images/PS3.jpg', 4, 4),
(16, 'PlayStation', '3 Slim', 'The PS3 Slim combines sleek design with ample storage space. Enjoy a vast array of games and media content in a more compact and efficient package.', '250GB HDD, PS1 Game Compatible', 'Cell Broadband Engine CPU', 'NVIDIA RSX GPU', '256MB RAM', '250GB HDD', 99.00, 'Images/PS3Slim.jpg', 3, 6),
(17, 'PlayStation', '3 Slim', 'The PS3 Slim combines sleek design with ample storage space. Enjoy a vast array of games and media content in a more compact and efficient package.PS3 Slim with increased storage 320GB capacity.', '320GB HDD, PS1 Game Compatible', 'Cell Broadband Engine CPU', 'NVIDIA RSX GPU', '256MB RAM', '320GB HDD', 109.00, 'Images/PS3Slim.jpg', 3, 4),
(18, 'PlayStation', '3 Slim', 'The PS3 Slim combines sleek design with ample storage space. Enjoy a vast array of games and media content in a more compact and efficient package. The PS3 Slim includes increased storage capacity 500GB.', '500GB HDD, PS1 Game Compatible', 'Cell Broadband Engine CPU', 'NVIDIA RSX GPU', '256MB RAM', '500GB HDD', 129.00, 'Images/PS3Slim.jpg', 4, 5),
(19, 'PlayStation', '3 Super Slim', 'The PS3 Super Slim 250GB offers a compact and lightweight design without sacrificing performance. Get ready to immerse yourself in a world of gaming and entertainment.', '250GB HDD, PS1 Game Compatible', 'Cell Broadband Engine CPU', 'NVIDIA RSX GPU', '256MB RAM', '250GB HDD', 99.00, 'Images/PS3SuperSlim.jpg', 3, 13),
(20, 'PlayStation', '3 Super Slim', 'The PS3 Super Slim 500GB offers a compact and lightweight design without sacrificing performance. Get ready to immerse yourself in a world of gaming and entertainment.', '500GB HDD, PS1 Game Compatible', 'Cell Broadband Engine CPU', 'NVIDIA RSX GPU', '256MB RAM', '500GB HDD', 129.00, 'Images/PS3SuperSlim.jpg', 4, 7),
(21, 'PlayStation', 'Vita', 'The PS Vita offers console-quality gaming on the go with its powerful hardware and vibrant OLED display. Enjoy a vast library of games and multimedia features in a portable package.', 'Portable Console, OLED Display', 'Quad-core ARM Cortex-A9 MPCore', 'Quad-core SGX543MP4+', '512MB RAM', '1GB Internal Memory + Memory C', 99.00, 'Images/PSVita.jpg', 4, 6),
(22, 'PlayStation', 'Vita v2', 'The PS Vita Slim combines sleek aesthetics with improved battery life, making it the perfect companion for gaming on the move. Experience immersive gameplay and entertainment wherever you go.', 'LCD Display, Longer Battery Life', 'Quad-core ARM Cortex-A9 MPCore', 'Quad-core SGX543MP4+', '512MB RAM', '1GB Internal Memory + Memory C', 129.00, 'Images/PSVita2.jpg', 4, 8),
(23, 'PlayStation', 'Portable', 'The PSP revolutionized handheld gaming with its robust library of games and multimedia capabilities. Take your gaming experience to the next level with this iconic portable console.', 'Portable Gaming, UMD Drive', 'MIPS R4000', '32MB RAM', '166MHz Graphics Core', 'UMD Drive', 63.00, 'Images/PSP.jpg', 4, 12),
(24, 'PlayStation', 'Portable Go', 'The PSP Go offers a compact and portable gaming experience with its slide-out controls and digital-only distribution. Access your favourite games and media content anytime, anywhere.', 'Digital Only PSP, Slide Out Controls', 'MIPS R4000', '166MHz Graphics Core', '32MB RAM', '16GB Internal Flash Memory', 79.00, 'Images/PSPGo.jpg', 3, 6),
(25, 'PlayStation', 'Portable Street', 'The PSP Street provides budget-friendly gaming on the go. With its lightweight design and extensive game library, it\'s perfect for casual gamers and enthusiasts alike.', 'No Wi-Fi, Portable Gaming', 'MIPS R4000', 'Sony GPU', '32MB RAM', '', 59.00, 'Images/PSPStreet.jpg', 3, 3),
(26, 'Xbox', 'Series X Refined', 'The Xbox Series X Refined offers cutting-edge performance and stunning graphics for immersive gaming experiences. With lightning-fast load times and robust features.', '2TB SSD, Ray-Tracing, 4K 120FPS, All Digital', 'Custom AMD Zen 2 CPU @ 3.8GHz', 'AMD RDNA 2 GPU @ 12.15TFLOPS', '16GB GDDR6', '2TB SSD', 449.00, 'Images/SeriesXRefresh.jpg', 5, 3),
(27, 'Xbox', 'Series S Refined', 'The Xbox Series S Refined delivers next-gen gaming performance in a compact package. With smooth gameplay and quick resume features, it\'s perfect for casual gamers and enthusiasts alike.', '1TB SSD, Ray-Tracing, All Digital', 'Custom AMD Zen 2 CPU @ 3.6GHz', 'AMD RDNA 2 GPU @ 4TFLOPS', '10GB GDDR6', '1TB SSD', 249.00, 'Images/SeriesSRefresh.jpg', 5, 4),
(28, 'Xbox', 'Series X', 'Experience true 4K gaming with the Xbox Series X. Featuring powerful hardware and advanced features, it delivers unparalleled performance and graphics for the ultimate gaming experience.', '1TB SSD, Ray-Tracing, 4K 120FPS', 'Custom AMD Zen 2 CPU @ 3.8GHz', 'Custom AMD RDNA 2 GPU @ 12.15T', '16GB GDDR6', '1TB SSD', 419.00, 'Images/SeriesX.jpg', 5, 6),
(29, 'Xbox', 'Series S', 'Enjoy next-gen gaming without breaking the bank with the Xbox Series S 512GB. With fast load times and smooth gameplay, it\'s the perfect console for budget-conscious gamers.', '512GB SSD, Ray-Tracing, Digital Only', 'Custom AMD Zen 2 CPU @ 3.6GHz', 'Custom AMD RDNA 2 GPU @ 4TFLOP', '10GB GDDR6', '512GB SSD', 229.00, 'Images/SeriesS.jpg', 4, 8),
(30, 'Xbox', 'Series S', 'The Xbox Series S 1TB offers expanded storage capacity for your games and media. With lightning-fast load times and stunning visuals, it delivers next-gen gaming experiences at an affordable price.', '1TB SSD, Ray-Tracing, Digital Only', 'Custom AMD Zen 2 CPU @ 3.6GHz', 'Custom AMD RDNA 2 GPU @ 4TFLOP', '10GB GDDR6', '1TB SSD', 285.00, 'Images/SeriesS.jpg', 5, 2),
(31, 'Xbox', 'One X', 'The Xbox One X delivers true 4K gaming and immersive entertainment experiences. With its powerful hardware and robust features, it\'s the ultimate choice for gamers seeking high-fidelity graphics.', '1TB HDD, 4K, HDR', 'Custom AMD 8-core CPU @ 2.3GHz', 'Custom AMD GPU @ 1.172GHz', '12GB GDDR5', '1TB HDD', 230.00, 'Images/OneX.jpg', 5, 9),
(32, 'Xbox', 'One S', 'Experience stunning visuals and enhanced performance with the Xbox One S 2TB. With ample storage space and 4K entertainment capabilities, it\'s perfect for gaming and multimedia enthusiasts.', '2TB HDD, Blue-Ray, HDR', 'Custom 1.75 GHz AMD 8-core APU', 'Integrated AMD graphics with 1', '8GB DDR3 RAM', '2TB HDD', 195.00, 'Images/OneS.jpg', 5, 2),
(33, 'Xbox', 'One S', 'The Xbox One S 1TB model provides sufficient storage for your games and media. With its compact design and 4K video streaming capabilities, it\'s a versatile entertainment hub for the whole family.', '1TB, Blue-Ray, HDR', 'Custom 1.75 GHz AMD 8-core APU', 'Integrated AMD graphics with 1', '8GB DDR3 RAM', '1TB HDD', 160.00, 'Images/OneS.jpg', 4, 10),
(34, 'Xbox', 'One S', 'Enjoy gaming and entertainment on a budget with the Xbox One S 500GB. With its compact size and powerful features, it\'s perfect for casual gamers and multimedia enthusiasts.', '500GB HDD, Blue-Ray, HDR', 'Custom 1.75 GHz AMD 8-core APU', 'Integrated AMD graphics with 1', '8GB DDR3 RAM', '500GB HDD', 115.00, 'Images/OneS.jpg', 4, 5),
(35, 'Xbox', 'One S Digital', 'Go all-digital with the Xbox One S Digital Edition. Stream your favourite movies and play digital games directly from the Microsoft Store. With its sleek design and affordable price.', '1TB HDD, Blue-Ray, HDR', 'Custom 1.75 GHz AMD 8-core APU', 'Integrated AMD graphics with 1', '8GB DDR3 RAM', '1TB HDD', 100.00, 'Images/OneSDigital.jpg', 3, 2),
(36, 'Xbox', 'One', 'The Xbox One 1TB model offers ample storage for your games and multimedia content. With its robust performance and enhanced features, it delivers an immersive gaming experience for players of all ages.', '1TB HDD, Multimedia Console', 'Custom 1.75 GHz AMD 8-core APU', '8GB DDR3 RAM', 'Integrated AMD graphics with 1', '1TB HDD', 110.00, 'Images/One.jpg', 4, 7),
(37, 'Xbox', 'One', 'The Xbox One 500GB provides reliable performance and entertainment features at an affordable price point. With its compact design and extensive game library, it\'s an excellent choice for casual gamers.', '500GB HDD, Multimedia Console', 'Custom 1.75 GHz AMD 8-core APU', '8GB DDR3 RAM', 'Integrated AMD graphics with 1', '500GB HDD', 100.00, 'Images/One.jpg', 3, 4),
(38, 'Xbox', '', 'The original Xbox console introduced gamers to a new era of gaming with its powerful hardware and innovative features. Experience classic titles and nostalgia-inducing gameplay with this iconic console.', 'Classic Titles, Xbox Live Connectivity', 'Intel Pentium III Coppermine', '64 MB DDR SDRAM', 'Custom 233 MHz NV2A-based GPU ', '8GB HDD (internal), DVD-ROM drive', 70.00, 'Images/Xbox.jpg', 4, 8),
(39, 'Xbox', '360', 'The Xbox 360 introduced HD gaming and online multiplayer to a wider audience. With its sleek design and robust features, it became one of the best-selling consoles of its generation.', '250GB HDD, Wireless Connectivity', '3.2 GHz PowerPC Tri-Core Xenon', 'Custom 500 MHz ATI Xenos', '512 MB GDDR3 RAM', '250GB HDD, DVD-ROM drive', 60.00, 'Images/Xbox360.jpg', 3, 6),
(40, 'Xbox', '360 S', 'The Xbox 360 S (Slim) model improved upon its predecessor with a sleeker design and quieter operation. It offered the same great gaming experience with enhanced reliability and additional storage options.', '250GB HDD, WiFi Connectivity', '3.2 GHz PowerPC Tri-Core Xenon', 'Custom 500 MHz ATI Xenos', '512 MB GDDR3 RAM', '250GB HDD, DVD-ROM drive', 70.00, 'Images/Xbox360S.jpg', 4, 4),
(41, 'Xbox', 'One S', 'The Xbox 360 S (Slim) model improved upon its predecessor with a sleeker design and quieter operation. It offered the same great gaming experience with enhanced reliability and additional storage options.', '320GB HDD, WiFi Connectivity', '3.2 GHz PowerPC Tri-Core Xenon', 'Custom 500 MHz ATI Xenos', '512 MB GDDR3 RAM', '320GB HDD, DVD-ROM drive', 77.00, 'Images/Xbox360S.jpg', 4, 4),
(42, 'Xbox', '360 E', 'The Xbox 360 E model featured a redesigned chassis and improved cooling system. With its spacious hard drive and extensive multimedia features, it provided an all-in-one entertainment solution for gamers and movie enthusiasts.', '250GB HDD, HDMI Connectivity', '3.2 GHz PowerPC Tri-Core Xenon', 'Custom 500 MHz ATI Xenos', '512 MB GDDR3 RAM', '250GB HDD, DVD-ROM drive', 85.00, 'Images/Xbox360E.jpg', 3, 6),
(43, 'Xbox', '360 E', 'The Xbox 360 E 500GB model offered ample storage space for games, movies, and other media content. With its sleek design and enhanced features, it provided a versatile entertainment experience for users.', '500GB HDD, HDMI Connectivity', '3.2 GHz PowerPC Tri-Core Xenon', 'Custom 500 MHz ATI Xenos', '512 MB GDDR3 RAM', '500GB HDD, DVD-ROM drive', 95.00, 'Images/Xbox360E.jpg', 4, 9),
(44, 'Nintendo', 'Switch OLED', 'The Nintendo Switch OLED model features a vibrant OLED screen, providing stunning visuals for gaming on the go. With its versatile design, improved audio, and enhanced battery life, it offers an immersive gaming experience for players of all ages.', '64GB Storage, Larger, OLED Display', 'NVIDIA Custom Tegra processor', 'NVIDIA Custom Tegra processor', '4GB LPDDR4 RAM', '64GB internal storage (expandable via microSD cards)', 270.00, 'Images/OLED.jpg', 5, 14),
(45, 'Nintendo', 'Switch', 'The Nintendo Switch combines the versatility of a handheld and a home console in one. With its innovative Joy-Con controllers and docked mode for TV play, it offers endless gaming possibilities. Its library includes popular titles from Nintendo franchises and third-party developers.', '32GB Storage, Portable and Docked Modes', 'NVIDIA Custom Tegra processor', 'NVIDIA Custom Tegra processor', '4GB LPDDR4 RAM', '32GB internal storage (expandable via microSD cards)', 249.00, 'Images/Switch.jpg', 5, 12),
(46, 'Nintendo', 'Switch Lite', 'The Nintendo Switch Lite is a compact, lightweight version of the original Switch, designed for handheld play. With its built-in controls and smaller form factor, it\'s perfect for gaming on the go. Despite its smaller size, it still offers access to a vast library of Nintendo Switch games.', '32GB Storage, Portable Only Console', 'NVIDIA Custom Tegra processor', 'NVIDIA Custom Tegra processor', '4GB LPDDR4 RAM', '32GB internal storage (expandable via microSD cards)', 185.00, 'Images/SwitchLite.jpg', 5, 8),
(47, 'Nintendo', 'Wii U', 'The Wii U 8GB model introduced the GamePad controller with a built-in touchscreen, offering innovative gameplay experiences. With its backward compatibility with Wii games and unique titles like \"Super Mario 3D World,\" it provided hours of entertainment for families and gamers alike.', '8GB HDD, Wii Games Compatibility', 'IBM PowerPC multi-core processor', 'AMD Radeon-based High Definition GPU', '2GB DDR3 RAM', '8GB internal flash memory (expandable via USB storage)', 84.00, 'Images/WiiU.jpg', 3, 6),
(48, 'Nintendo', 'Wii U', 'The Wii U 32GB model offered increased storage capacity for downloading games and content from the Nintendo eShop. With its unique dual-screen gameplay and innovative features, it provided a one-of-a-kind gaming experience for players of all ages.', '32GB HDD, Wii Games Compatibility', 'IBM PowerPC multi-core processor', 'AMD Radeon-based High Definition GPU', '2GB DDR3 RAM', '32GB internal flash memory (expandable via USB storage)', 95.00, 'Images/WiiU.jpg', 4, 7),
(49, 'Nintendo', 'Wii', 'The Wii offered motion-controlled gaming and a vast library of family-friendly titles. With its intuitive Wii Remote controller and classic games like \"Wii Sports,\" it provided hours of entertainment for players of all ages.', 'Motion Control Wiimote, GameCube Game Compatibility', 'IBM Broadway processor', 'ATI Hollywood GPU', '88MB main memory', 'None (supports SD card storage)', 69.00, 'Images/Wii.jpg', 5, 6),
(50, 'Nintendo', 'Wii Family Edition', 'The Wii Family Edition offered motion-controlled gaming and a vast library of family-friendly titles. With its intuitive Wii Remote controller and classic games like \"Wii Sports,\" it provided hours of entertainment for players of all ages.', 'Motion Control Wiimote, Cheaper Alternative', 'IBM Broadway processor', 'ATI Hollywood GPU', '88MB main memory', 'None (supports SD card storage)', 55.00, 'Images/WiiFamily.jpg', 3, 6),
(51, 'Nintendo', 'Wii Mini', 'The Wii Mini offered a compact, budget-friendly option for enjoying Wii games. With its simplified design and compatibility with a vast library of Wii titles, it provided affordable entertainment for casual gamers and families.', 'Motion Control Wiimote, Cheaper Alternative', 'IBM Broadway processor', 'ATI Hollywood GPU', '88MB main memory', 'None (supports SD card storage)', 49.00, 'Images/WiiMini.jpg', 3, 3),
(52, 'Nintendo', 'SNES Classic', 'The Super NES Classic Edition is a miniaturized replica of the iconic Super Nintendo Entertainment System. It comes preloaded with 21 classic games, allowing players to relive the golden age of 16-bit gaming.', '21 Classic Games Pre-Loaded, HDMI Connectivity', 'Ricoh 5A22 processor', 'Custom Ricoh 5C33', '128KB RAM', '512MB NAND flash memory', 65.00, 'Images/SNESClassic.jpg', 4, 5),
(53, 'Nintendo', 'NES Classic', 'The NES Classic Edition is a miniature replica of the original Nintendo Entertainment System, featuring a collection of 30 iconic NES games,  it\'s perfect for retro gaming enthusiasts.', '30 Classic Games Pre-Loaded, HDMI Connectivity', 'Allwinner R16', 'ARM Mali400MP2', '256MB DDR3 RAM', '512MB NAND flash memory', 40.00, 'Images/NESClassic.jpg', 4, 6),
(54, 'Nintendo', 'Entertainment System', 'The Nintendo Entertainment System revolutionized the gaming industry and introduced players to iconic franchises like \"Super Mario Bros.,\" \"The Legend of Zelda,\" and \"Metroid.\" With its simple yet addictive gameplay and memorable 8-bit graphics, it remains a beloved console for retro gaming enthusia', '8-Bit Graphics, Cartridge Games', 'Ricoh 2A03 8-bit processor', 'Ricoh RP2C02 Picture Processing Unit (PPU)', '2KB RAM', 'Cartridges', 65.00, 'Images/NES.jpg', 4, 8),
(55, 'Nintendo', 'Super Entertainment System', 'The Super Nintendo Entertainment System elevated gaming with its 16-bit graphics, immersive sound, and iconic library of games. From classics like \"Super Mario World\" and \"The Legend of Zelda: A Link to the Past\" to innovative titles like \"Star Fox\" and \"Super Metroid,\" it offered endless entertainm', '16-Bit Graphics, Cartridge Games', 'Ricoh 5A22 processor', 'Custom Ricoh 5C33', '128KB RAM', 'Cartridges', 72.00, 'Images/SNES.jpg', 4, 9),
(56, 'Nintendo', 'GameCube', 'The Nintendo GameCube introduced compact discs and brought forth a diverse library of games, including \"Super Smash Bros. Melee,\" \"The Legend of Zelda: The Wind Waker,\" and \"Metroid Prime.\" Its innovative controller design and unique games made it a favourite among Nintendo fans.', 'Mini-DVD Discs, Cube Design', 'IBM PowerPC \"Gekko\"', 'ATI \"Flipper\"', '43MB total', 'MiniDVD discs', 70.00, 'Images/Gamecube.jpg', 4, 15),
(57, 'Nintendo', 'Parasonic Q', 'The Nintendo GameCube introduced compact discs and brought forth a diverse library of games, including \"Super Smash Bros. Melee,\" \"The Legend of Zelda: The Wind Waker,\" and \"Metroid Prime.\" Its innovative controller design and unique games made it a favourite among Nintendo fans.', 'ULTRA RARE, Mini-DVD Discs, Cube Design', 'IBM PowerPC \"Gekko\"', 'ATI \"Flipper\"', '43MB total', 'MiniDVD discs', 1300.00, 'Images/ParasonicQ.jpg', 3, 2),
(58, 'Nintendo', 'Game and Watch', 'The Nintendo Game & Watch series paved the way for handheld gaming with its simple yet addictive gameplay. These pocket-sized devices featured LCD screens and single-game experiences, including classics like \"Ball,\" \"Mario\'s Cement Factory,\" and \"Donkey Kong.\"', 'RARE, LCD Screen, Pocket-Sized Device', 'Custom 4-bit Sharp SM5xx CPU', '', '', '', 80.00, 'Images/Gameandwatch.jpg', 3, 5),
(59, 'Nintendo', 'Game Boy', 'The Game Boy revolutionized portable gaming with its compact design and long battery life. With iconic titles like \"Tetris,\" \"Super Mario Land,\" and \"The Legend of Zelda: Link\'s Awakening,\" it became one of Nintendo\'s best-selling consoles, defining handheld gaming for generations.', 'Portable Gaming, Cartridge Games', 'Custom Sharp LR35902', '', '8KB RAM', '', 70.00, 'Images/GameBoy.jpg', 4, 6),
(60, 'Nintendo', 'Game Boy Pocket', 'The Game Boy Pocket refined the original Game Boy\'s design, offering a slimmer profile and improved screen contrast. Despite its smaller size, it retained compatibility with the vast library of Game Boy games, making it a popular choice for gaming on the go.', 'Portable Gaming, Cartridge Games', 'Custom Sharp LR35902', '', '8KB RAM', '', 45.00, 'Images/GameBoyPocket.jpg', 4, 2),
(61, 'Nintendo', 'Game Boy Light', 'The Game Boy Light was an enhanced version of the Game Boy Pocket, featuring a backlit screen for improved visibility in low-light conditions. Released exclusively in Japan, it offered gamers enhanced portability and convenience for gaming anytime, anywhere.', 'RARE Japanese Exclusive, Cartridge Games', 'Custom Sharp LR35902', '', '8KB RAM', '', 75.00, 'Images/GameBoyLight.jpg', 4, 3),
(62, 'Nintendo', 'Game Boy Color', 'The Game Boy Color marked Nintendo\'s transition to full-colour handheld gaming. With a vibrant display and backward compatibility with original Game Boy games, it delivered a diverse gaming experience.', 'Coloured LCD Screen, Cartridge Games', 'Custom Sharp LR35902', '', '32KB RAM', '', 65.00, 'Images/GameBoyColor.jpg', 4, 5),
(63, 'Nintendo', 'Game Boy Advance', 'The Game Boy Advance introduced powerful 32-bit gaming to the handheld market. Its ergonomic design, improved graphics, and extensive library of games made it a favourite among gamers. ', '32-Bit Graphics, Cartridge Games', '32-bit ARM7TDMI', '96KB VRAM', '32KB WRAM', '', 76.00, 'Images/GameBoyAdvance.jpg', 5, 4),
(64, 'Nintendo', 'Game Boy Advance SP', 'The Game Boy Advance SP introduced a clamshell design and a front-lit screen, enhancing portability and usability. Its rechargeable battery and compact form factor made it ideal for gaming on the go. With a vast library of games and improved screen visibility, it remains a beloved handheld console.', '32-Bit Graphics, Foldable Screen, Cartridge Games', '32-bit ARM7TDMI', '96KB VRAM', '32KB WRAM', '', 89.00, 'Images/GameBoyAdvanceSP.jpg', 5, 5),
(65, 'Nintendo', 'Game Boy Micro', 'The Game Boy Micro offered a compact and stylish gaming experience, featuring a vibrant backlit screen and interchangeable faceplates. Despite its small size, it delivered impressive performance and compatibility with Game Boy Advance games, making it a unique addition to the Game Boy family.', 'Vibrant Backlit Screen, GBA Game Compatibility', '32-bit ARM7TDMI', '32KB WRAM', '96KB VRAM', '', 65.00, 'Images/GameBoyMicro.jpg', 4, 3),
(66, 'Nintendo', 'DS', 'The Nintendo DS revolutionized handheld gaming with its dual-screen design and touchscreen interface. It offered innovative gameplay experiences, including stylus-based controls and wireless multiplayer.  ', 'Dual Screens, Touchscreen, Cartridge Games', 'Two ARM processors (67 MHz and 33 MHz)', '', '4MB RAM', '', 60.00, 'Images/DS.jpg', 5, 6),
(67, 'Nintendo', 'DS Lite', 'Building on the success of the original DS, the DS Lite featured a slimmer design, brighter screens, and improved battery life. Its portable form factor and extensive game library made it a favourite among gamers of all ages.', 'Brighter Screens, GBA Game Compatibility', 'Two ARM processors (133 MHz and 33 MHz)', '', '4MB RAM', '', 75.00, 'Images/DSLite.jpg', 5, 6),
(68, 'Nintendo', 'DSi', 'The Nintendo DSi introduced new features like dual cameras, enhanced online functionality, and the ability to download games from the Nintendo DSi Shop. It offered a range of multimedia capabilities and access to a growing library of downloadable games, apps, and DSiWare titles.', 'Dual Screens, Touchscreen, Cartridge Games', 'Two ARM processors (133 MHz and 33 MHz)', '', '16MB RAM', '', 79.00, 'Images/DSi.jpg', 4, 6),
(69, 'Nintendo', 'DSi XL', 'The Nintendo DSi XL featured larger screens and a wider viewing angle, providing a more immersive gaming experience. Its increased size and improved stylus made it comfortable to use for extended gaming sessions.', 'Larger Dual Screens, Touchscreen, Cartridge Games', 'Two ARM processors (133 MHz and 33 MHz)', '', '16MB RAM', '', 90.00, 'Images/DSiXL.jpg', 4, 3),
(70, 'Nintendo', '3DS', 'The Nintendo 3DS introduced glasses-free 3D gaming, providing a new dimension of gameplay immersion. It featured a robust line-up of first-party and third-party titles, including \"The Legend of Zelda: Ocarina of Time 3D,\" \"Super Mario 3D Land,\" and \"Pokémon X and Y.\"', 'Dual Screens, Touchscreen, 3DS Mode', 'Dual-core ARM11 MPCore', '', '128MB FCRAM', '', 90.00, 'Images/3DS.jpg', 5, 8),
(71, 'Nintendo', '3DS XL', 'The Nintendo 3DS XL offered larger screens and a more comfortable grip, enhancing the handheld gaming experience. Its extended battery life and improved 3D viewing angles made it ideal for gaming on the go. Access to the Nintendo eShop and a vast library of downloadable games.', 'Larger Dual Screens, Touchscreen, 3DS Mode', 'Dual-core ARM11 MPCore', '', '128MB FCRAM', '', 100.00, 'Images/3DSXL.jpg', 5, 7),
(72, 'Nintendo', '2DS', 'The Nintendo 2DS offered an affordable entry point into the world of Nintendo 3DS gaming. With its unique slate-like design and lack of 3D functionality, it was a popular choice for younger gamers and families.', 'Dual Screens, Touchscreen, No 3DS Mode', 'Dual-core ARM11 MPCore', '', '128MB FCRAM', '', 75.00, 'Images/2DS.jpg', 4, 6),
(73, 'Nintendo', 'New 3DS', 'The New Nintendo 3DS introduced enhanced processing power, improved 3D tracking, and additional control features like the C-Stick and ZL/ZR buttons. It offered exclusive games and experiences, such as \"Xenoblade Chronicles 3D\" and \"Super Nintendo Virtual Console\" titles.', 'Dual Screens, Touchscreen, 3DS Mode, Amiibo Compatibility', 'Quad-core ARM11 MPCore', '', '256MB FCRAM', '', 110.00, 'Images/New3DS.jpg', 5, 4),
(74, 'Nintendo', 'New 3DS XL', 'The New Nintendo 3DS XL offered the ultimate handheld gaming experience with its larger screens, improved 3D viewing angles, and extended battery life. It provided access to a vast library of games, including exclusive titles and Virtual Console classics.', 'Larger Dual Screens, Touchscreen, 3DS Mode, Amiibo Compatibility', 'Quad-core ARM11 MPCore', '', '256MB FCRAM', '', 120.00, 'Images/New3DSXL.jpg', 4, 8),
(75, 'Sega', 'SG-1000', 'The Sega SG-1000 was Sega\'s first home video game console, released in 1983. It featured a library of games primarily released on ROM cartridges, offering titles like \"Zaxxon,\" \"Hang-On,\" and \"Space Invaders.\"', 'Sega\'s First Console, ROM cartridges', 'NEC 780C (Zilog Z80 clone)', 'Texas Instruments TMS9918', '1KB RAM', 'ROM cartridges', 120.00, 'Images/SG1000.jpg', 3, 6),
(76, 'Sega', 'Master System', 'The Sega Master System, released in 1985, was Sega\'s second home console and a direct competitor to the NES. With improved graphics and sound capabilities, it offered iconic titles like \"Sonic the Hedgehog,\" \"Alex Kidd in Miracle World,\" and \"Phantasy Star.\"', 'Improved Graphics and Sound, Sonic Debut', 'Zilog Z80A', 'Texas Instruments TMS9918/315-5124', '8KB RAM', 'ROM cartridges', 100.00, 'Images/MasterSystem.jpg', 4, 4),
(77, 'Sega', 'Mega Drive', 'The Sega Mega Drive, released in 1988, was Sega\'s third home console and a major success worldwide. With its iconic library of games, including \"Sonic the Hedgehog,\" \"Streets of Rage,\" and \"Golden Axe,\" it became one of the best-selling consoles of its era.', 'Improved Graphics, Iconic Games Library', 'Motorola 68000', 'VDP (Video Display Processor)', '64KB RAM', 'ROM cartridges', 110.00, 'Images/MegaDrive.jpg', 5, 11),
(78, 'Sega', 'Mega CD', 'The Sega Mega CD, released as the Sega CD in North America, was an add-on peripheral for the Sega Mega Drive that allowed for CD-ROM-based gaming. It offered enhanced graphics, full-motion video, and CD-quality audio, expanding the capabilities of the Mega Drive.', 'Add-On for Mega Drive that Improves Performance', 'Motorola 68000', 'VDP (Video Display Processor)', 'Varies by model', 'CD-ROM', 185.00, 'Images/MegaCD.jpg', 4, 2),
(79, 'Sega', '32X', 'The Sega 32X was an add-on peripheral for the Sega Mega Drive, released in 1994, designed to provide 32-bit gaming capabilities. Despite offering enhanced graphics and processing power, its limited library of games and compatibility issues with the Sega Saturn hindered its success.', 'Add-On for Mega Drive that Improves Performance', 'Two Hitachi SH-2 CPUs', 'Custom ASIC', '256KB RAM', 'ROM cartridges', 90.00, 'Images/Sega32X.jpg', 3, 4),
(80, 'Sega', 'Saturn', 'Released in 1994, the Sega Saturn was Sega\'s entry into the 32-bit era of gaming. Despite facing stiff competition from the Sony PlayStation and Nintendo 64, it boasted impressive 2D graphics and a diverse library of games.', '32-Bit Graphics, Diverse Library of Games', 'Hitachi SH-2', 'VDP1 and VDP2', '2MB RAM', 'CD-ROM', 140.00, 'Images/SegaSaturn.jpg', 4, 6),
(81, 'Sega', 'Dreamcast', 'The Sega Dreamcast, released in 1999, was Sega\'s final home console and a pioneer of many modern gaming features. It introduced innovations like online gaming, built-in modem support, and a visual memory unit (VMU).', 'Online Gaming, Built-In Modem Support', 'Hitachi SH-4', 'PowerVR2', '16MB RAM', 'GD-ROM', 95.00, 'Images/Dreamcast.jpg', 5, 6),
(82, 'Sega', 'Mega Drive Mini', 'The Sega Mega Drive Mini is a miniature replica of the original Sega Mega Drive console, released in 2019 as part of Sega\'s celebration of its gaming heritage. It comes pre-loaded with a selection of classic games.', 'Classic Games Pre-Loaded, HDMI Connectivity', 'ARM Cortex-A35', 'Varies by model', 'Varies by model', 'Flash memory', 55.00, 'Images/MegaDriveMini.jpg', 4, 5),
(83, 'Sega', 'Game Gear', 'Launched in 1990, the Sega Game Gear was Sega\'s response to Nintendo\'s Game Boy. It featured a full-colour backlit screen and superior graphics compared to its monochrome competitor.', 'Full-Colour Screen, Great Graphics', 'Zilog Z80', 'VDP', 'Varies by model', 'Cartridges', 60.00, 'Images/GameGear.jpg', 3, 6),
(84, 'Sega', 'Mega Jet', 'The Sega Mega Jet was a portable version of the Sega Mega Drive released exclusively for use on Japan Airlines flights in the mid-1990s. Passengers could enjoy gaming entertainment during their flights by connecting the console to built-in seat monitors. ', 'VERY RARE, Japanese Exclusive, Handheld Console', 'Motorola 68000', 'VDP', 'Varies by configuration', 'Cartridges', 300.00, 'Images/MegaJet.jpg', 4, 3),
(85, 'Sega', 'Nomad', 'The Sega Nomad, released in 1995, was a handheld console that could play Sega Genesis/Mega Drive games on the go. It featured a full-color backlit screen and compatibility with Genesis cartridges, making it a portable alternative to the home console. Despite its innovative concept, it faced challeng', 'VERY RARE, Handheld Console', 'Motorola 68000', 'VDP', 'Varies by configuration', 'Cartridges', 200.00, 'Images/Nomad.jpg', 4, 5),
(86, 'PlayStation', 'Classic', 'Released in 2018, the PlayStation Classic is a miniature replica of the original PlayStation console, preloaded with 20 iconic games from the 32-bit era. It features HDMI output for modern TVs and includes two replica controllers for multiplayer gaming.', '20 Classic Games Pre-Loaded, HDMI Connectivity', 'MediaTek MT8167A Quad-Core ARM Cortex-A35', 'PowerVR GE8300', '1 GB DDR3 SDRAM', '16 GB eMMC flash memory', 45.00, 'Images/PSClassic.jpg', 3, 8);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`prod_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `prod_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=87;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
